### ISSUE TITLE
Does not avoid duplicates in output POT files

### ISSUE THREAD

**Issue by konoufo** [alexanderwallin/babel-plugin-react-gettext-parser#1]
So i know the `getUniqueBlocks` function does a good job. But it looks like 'state' is maintained in the `traverser` provided by react-gettext-parser which results in outputting to file the previously found blocks each time babel `exit` the `traverser`. Which means that it happens at every transpiled file matched by a glob, when doing something like this :
`babel --plugins react-gettext-parser  'asp_react/apps/**/{*.jsx,js}'`
Now this is to be expected as, without babel, react-gettext-parser would call 'exit' once it's done with all the files and would not have to call it again. I suspect this isn't the case here because babel is feeding the files one at a time to the plugin.

**Comment by alexanderwallin** [comment]
Resolved by #2.

I took the opportunity to publish this package to npm.
